# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

tensor = torch.rand(7,7)
tensor


# Create random tensor


tensor([[0.4890, 0.9186, 0.9975, 0.8389, 0.6263, 0.7666, 0.5610],
        [0.4903, 0.4086, 0.6839, 0.5658, 0.2178, 0.8120, 0.5976],
        [0.0736, 0.8357, 0.3762, 0.1326, 0.1537, 0.4893, 0.2415],
        [0.3961, 0.6796, 0.2561, 0.7085, 0.7786, 0.2148, 0.6869],
        [0.6816, 0.9697, 0.0041, 0.5193, 0.2048, 0.3554, 0.8278],
        [0.2144, 0.8997, 0.6218, 0.6181, 0.0213, 0.2049, 0.8418],
        [0.1642, 0.8921, 0.6722, 0.8142, 0.2541, 0.9754, 0.7924]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor2 = torch.rand(1,7)
print(tensor2)
print(tensor.shape)
print(tensor2.shape)
# Perform matrix multiplication 
print(torch.matmul(tensor, tensor2.T))

tensor([[0.0097, 0.5710, 0.0193, 0.6337, 0.4068, 0.9315, 0.5154]])
torch.Size([7, 7])
torch.Size([1, 7])
tensor([[2.3381],
        [1.7628],
        [1.2120],
        [1.7167],
        [1.7304],
        [1.5529],
        [2.4603]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
torch.manual_seed(0)
tensor = torch.rand(7,7)
print(tensor)
# Create another random tensor
torch.manual_seed(0)
tensor2 = torch.rand(1,7)
print(tensor2)
print(tensor.shape)
print(tensor2.shape)
# Perform matrix multiplication 
result = torch.matmul(tensor, tensor2.T)
print(result, result.shape)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
torch.Size([7, 7])
torch.Size([1, 7])
tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = 'cpu'
if torch.cuda.is_available():
    device = "cuda"
    torch.cuda.manual_seed(1234)
elif torch.backends.mps.is_available():
    device = "mps"
# Create two random tensors on GPU
print(device)
tensor_gpu = torch.rand((2,3), device=device)
tensor2_gpu = torch.rand((2,3), device=device)

print(tensor_gpu, tensor_gpu.device)
print(tensor2_gpu, tensor2_gpu.device)

cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') cuda:0
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0') cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [41]:
# Perform matmul on tensor_A and tensor_B
result_gpu = torch.matmul(tensor_gpu, tensor2_gpu.T)

### 8. Find the maximum and minimum values of the output of 7.

In [46]:
# Find max
print(result_gpu.max())
# Find min
print(result_gpu.min())


tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [47]:
# Find arg max
print(tensor_gpu.argmax())

# Find arg min
print(tensor_gpu.argmin())

tensor(5, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [48]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_f = torch.rand(1,1,1,10)
print(tensor_f)

# Remove single dimensions
tensor_f_single = tensor_f.squeeze()
print(tensor_f_single)

# Print out tensors and their shapes
print(tensor_f.shape)
print(tensor_f_single.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([1, 1, 1, 10])
torch.Size([10])
