In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
random_tensor = torch.rand(size = (3,4))
random_tensor, random_tensor.dtype

(tensor([[0.9589, 0.8811, 0.4118, 0.2691],
         [0.6852, 0.7315, 0.4057, 0.8639],
         [0.2228, 0.2383, 0.1430, 0.0656]]),
 torch.float32)

In [19]:
random_image_tensor = torch.rand(224, 224, 3)
random_image_tensor, random_image_tensor.dtype

(tensor([[[0.5588, 0.7385, 0.1251],
          [0.0833, 0.8362, 0.3359],
          [0.0128, 0.7618, 0.6104],
          ...,
          [0.3968, 0.5311, 0.4182],
          [0.8062, 0.2857, 0.6328],
          [0.4646, 0.0596, 0.7176]],
 
         [[0.0331, 0.7405, 0.1242],
          [0.5853, 0.0334, 0.2814],
          [0.7921, 0.2956, 0.6901],
          ...,
          [0.4208, 0.8063, 0.0405],
          [0.7956, 0.8188, 0.6632],
          [0.4122, 0.4027, 0.8613]],
 
         [[0.3502, 0.9895, 0.5823],
          [0.1877, 0.2831, 0.3123],
          [0.2416, 0.2444, 0.7758],
          ...,
          [0.0270, 0.9643, 0.3965],
          [0.5345, 0.8167, 0.7602],
          [0.6528, 0.7282, 0.3526]],
 
         ...,
 
         [[0.9895, 0.7593, 0.0476],
          [0.2133, 0.1745, 0.7851],
          [0.3400, 0.3404, 0.3630],
          ...,
          [0.5231, 0.5517, 0.0244],
          [0.3346, 0.5761, 0.0230],
          [0.5562, 0.4202, 0.7431]],
 
         [[0.9844, 0.2860, 0.6324],
          [0

In [21]:
zeroes = torch.zeros(10)
zeroes

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
zeroes = torch.zeros(size=(4,6))
zeroes

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [24]:
ones = torch.ones(size=(3, 39))
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1.]])

In [25]:
zero_to_ten = torch.arange(1, 10)
zero_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ten_zeroes = torch.zeros_like(input = zero_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
ten_ones = torch.ones_like(input=ten_zeroes)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [36]:
float32_tensor = torch.tensor([3, 6, 9], dtype=None, device=None, requires_grad=False)
float32_tensor.shape, float32_tensor.dtype, float32_tensor.device

(torch.Size([3]), torch.int64, device(type='cpu'))

In [37]:
ten_ones + 1
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [38]:
ten_ones = ten_ones + 1
ten_ones

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [40]:
ten_twos = ten_ones
ten_twos

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [41]:
ten_twos * ten_twos

tensor([4, 4, 4, 4, 4, 4, 4, 4, 4])

In [43]:
torch.matmul(ten_twos, ten_twos)

tensor(36)

In [44]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)


In [45]:
torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [47]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [49]:
print(tensor_A.ndim)
print(tensor_B.ndim)

2
2


In [ ]:
print(tensor_A.shape)
print(tensor_B.shape)

In [50]:
print(tensor_A.T)

tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [51]:
torch.manual_seed(42)
linear = torch.nn.Linear(
    in_features=2,
    out_features=6
)
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [53]:
torch.arange(0, 100, 10)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 1.0
Maximum: 6.0
Mean: 3.5
Sum: 21.0


In [55]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(6.), tensor(1.), tensor(3.5000), tensor(21.))

In [56]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [57]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [60]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [66]:
tensor = tensor.reshape((3,3))
tensor

tensor([[10., 20., 30.],
        [40., 50., 60.],
        [70., 80., 90.]])

In [67]:
tensor[0:2, 0:2]

tensor([[10., 20.],
        [40., 50.]])

In [69]:
tensor[:, 1]

tensor([20., 50., 80.])

In [71]:
import numpy as np

array = np.arange(1, 11)
tensor = torch.tensor(array)
tensor, tensor.dtype, array, array.dtype

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.int64,
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 dtype('int64'))

In [79]:
random_seed = 42

torch.manual_seed(seed = random_seed)
random_tensor_A = torch.rand(3, 4)
torch.manual_seed(42)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor B:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [80]:
!nvidia-smi

Fri Jan 17 09:33:42 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.72                 Driver Version: 566.14         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   41C    P0             12W /   80W |       0MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [82]:
torch.cuda.is_available()

True

In [83]:
device = "cpu"
if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"

In [84]:
device

'cuda'

In [85]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [86]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])